apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: {{ .Values.environment }}
  annotations:
    'moniker.spinnaker.io/stack': {{ .Values.environment }}
  labels:
    app: demo
    env: {{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: demo
    env: {{ .Values.environment }}
